server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8080/eureka/'

spring:
  application:
    name: 'article-service'
  datasource:
    url: 'jdbc:h2:mem:articles'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: 'pass'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: 'update'
  h2:
    console:
      enabled: true
      path: '/h2'
      settings:
        web-allow-others: true