server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8080/eureka/'

spring:
  application:
    name: 'gateway-service'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: 'productService'
          uri: 'lb://product-service'
          predicates:
            - Path=/product/**
        - id: 'articleService'
          uri: 'lb://article-service'
          predicates:
            - Path=/article/**